version: '3.6'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sleep", "infinity"]
    networks:
      - my-service
    ports:
      - "8000:8000"
    volumes:
      - "./package.json:/opt/service/package.json"
      - "./app.js:/opt/service/app.js"
      - "./src:/opt/service/src"
      - ".eslintrc:/opt/service/.eslintrc"
    environment:
      - DB_ACCESS_URL=http+tcp://db:8529
      - DB_NAME=mydb
      - DB_USERNAME=myuser
      - DB_PASSWORD=myuserpassword
    depends_on:
      - db
  db:
    image: arangodb:3.3
    volumes:
      - "dbdata:/var/lib/arangodb3"
      - "./init/db-init.sh:/docker-entrypoint-initdb.d/db-init.sh"
    environment:
      - ARANGO_SERVER_ENDPOINT=unix:///tmp/arangodb-tmp.sock
      - ARANGO_ROOT_PASSWORD=myrootpassword
      - DB_NAME=mydb
      - DB_USERNAME=myuser
      - DB_PASSWORD=myuserpassword
    networks:
      - my-service
    ports:
      - "8529:8529"
  nginx:
    image: nginx
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    volumes:
      - ./nginx/site.template:/etc/nginx/conf.d/site.template
    environment:
      - UPSTREAM_HOST=app:8000
    networks:
      - my-service
    ports:
      - "8080:80"

networks:
  my-service:

volumes:
  dbdata:
